version: '3'

services:
  websocket-service:
    image: gregszalay/websocket-service:v1.0
    build: .
    command: /app/websocket-service
    volumes:
      #- ./websocket-service/credentials/PRIVATE.json:/tmp/keys/PRIVATE.json:ro
      - ./websocket-service/credentials:/tmp/keys:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/PRIVATE.json
      - GCP_PROJECT_ID=${FIREBASE_PROJECT_CODE}
      - SERVICE_APP_NAME=device-service
      # LOG_LEVEL Panic, Fatal, Error, Warn, Info, Debug, Trace
      - LOG_LEVEL=Info
      - DEVICE_SERVICE_HOST=device-service
      - DEVICE_SERVICE_PORT=5000
      - DEVICE_SERVICE_GET_STATION_URL=/chargingstations/station
      - SERVER_TLS_CERT_FILE=/tmp/keys/fullchain.pem
      - SERVER_TLS_KEY_FILE=/tmp/keys/privkey.pem
      - CLIENT_TLS_CERT_FILE=/tmp/keys/client_cert.pem
    ports:
      - "3000:3000"
  device-service:
    image: gregszalay/device-service:v1.0
    build: .
    command: /app/device-service
    volumes:
      - ./device-service/credentials/PRIVATE.json:/tmp/keys/PRIVATE.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/PRIVATE.json
      - GCP_PROJECT_ID=${FIREBASE_PROJECT_CODE}
      - SERVICE_APP_NAME=websocket-service
      # LOG_LEVEL Panic, Fatal, Error, Warn, Info, Debug, Trace
      - LOG_LEVEL=Info
    ports:
      - "5000:5000"
  user-service:
    image: gregszalay/user-service:v1.0
    build: .
    command: /app/user-service
    volumes:
      - ./user-service/credentials/PRIVATE.json:/tmp/keys/PRIVATE.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/PRIVATE.json
      - GCP_PROJECT_ID=${FIREBASE_PROJECT_CODE}
      - SERVICE_APP_NAME=user-service
      # LOG_LEVEL Panic, Fatal, Error, Warn, Info, Debug, Trace
      - LOG_LEVEL=Info
  transaction-service:
    image: gregszalay/transaction-service:v1.0
    build: .
    command: /app/transaction-service
    volumes:
      - ./transaction-service/credentials/PRIVATE.json:/tmp/keys/PRIVATE.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/PRIVATE.json
      - GCP_PROJECT_ID=${FIREBASE_PROJECT_CODE}
      - SERVICE_APP_NAME=transaction-service
      # LOG_LEVEL Panic, Fatal, Error, Warn, Info, Debug, Trace
      - LOG_LEVEL=Info
    # TODO: configure container for frontend-service 
    #  frontend-service:
    #   build:
    #    context: ./frontend-service
    #   dockerfile: Dockerfile
    #  volumes:
    #   - ./frontend-service/src:/app/src
    #command: npm run start
    #ports:
    # - "8085:8085"

    #    environment: #NODE_ENV: development
